spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/auth/**
            - Method=GET, POST
        - id: member-service-passport
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
            - Method=GET, POST, PUT, DELETE
          filters:
            - PassportFilter